### ISSUE TITLE
Any plans to port to another language?

### ISSUE THREAD

**Issue by Maleus** [codeexpress/respounder#1]
I would love to implement this into our corporate scanning, but I am not allowed to install go. Any plans to port it to something like Python or Ruby?

**Comment by codeexpress** [comment]
You don't need to install golang in order to use Respounder. Pre-built native binaries are available in the releases section here: https://github.com/codeexpress/respounder/releases

You should be able to download the relevant executable and run it directly on the machine without need of any language interpreter or runtime.
